<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sampleEditor" nsURI="http://www.example.org/sampleEditor" nsPrefix="sampleEditor">
  <eClassifiers xsi:type="ecore:EClass" name="root">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childA" eType="#//A"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childB" eType="#//B"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childC" eType="#//C"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//root"/>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//A"/>
  <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="#//B"/>
</ecore:EPackage>
